#! /usr/bin/env python3

import re
import sys
from datetime import datetime


if sys.argv[1] == "-":
   body = sys.stdin.read()
else:
   with open(sys.argv[1], "r") as f:
      body = f.read()

times = re.findall( r"1[0-9]{9}\.?[0-9]*", body) # Will work until 2033, decimal is optional
times = list(set( times ))
times = [(t, float(t)) for t in times]

times.sort(key=lambda x: x[1])

print( times[0] )
anchorTime = times[0][1]

for tStr,t in times:
   tNorm = t-anchorTime
   body = body.replace( tStr, str(tNorm) )

print( body, end="" )


print( f"Used {anchorTime} as anchor. This corresponds to date: {datetime.fromtimestamp(anchorTime)}" )
